### ISSUE TITLE
KF 1.0 Pipelines

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/manifests#33]

**Comment by LaVLaS** [comment]
Initial deployment of KF pipelines was successful major issue is that any pipeline that needs to pass artifacts between steps needs to assign an `emptyDir` volume to the containers.  The default KF pipelines are reporting the same issue outlined in #17.

**Comment by LaVLaS** [comment]
I was able to deploy basic hello-world pipelines successfully. Advanced pipelines that require mounting volumes to pass artifacts between steps will need use [emptyDir](https://argoproj.github.io/argo/fields/#emptydirvolumesource).

This version of Argo (2.3.0) deployed in KF1.0 is an older version that creates attempts to create output artifacts in `/argo/output`. This will result in the Argo workflow failing due to 'mkdir: /argo/output permission denied'. This error is fixed in newer versions of Argo. See https://github.com/argoproj/argo/issues/1445). A workaround for this issue is to grant the `anyuid` to the serviceaccount assigned to the pipeline

```
oc adm policy add-scc-to-user anyuid -z pipeline-runner -n kubeflow
```
